### ISSUE TITLE
possible type in type string in spec.ini

### ISSUE THREAD

**Issue by eps1lon** [OmegaK2/PyPoE#25]
There is currently one field (PassiveSkills#Icon_DDSFile) which contains `ref|string#` as a type string in https://github.com/OmegaK2/PyPoE/blob/dev/PyPoE/_data/dat.specification.ini. Does the `#` serve a purpose or is this just a typo?

More asking for myself since im writing a sql parser which uses this file.

**Comment by OmegaK2** [comment]
```#``` is a comment delimiter. When configobj parses the file you should get ref|string as type and the ```#```  is ignored. But indeed the ```#```  doesn't serve a purpose there and is a typo indeed since there is no comment.

**Comment by eps1lon** [comment]
Alright. I'm currently parsing this to json with a nearley grammar but i'm currently manually removing the comments since it clutters the grammar. 

You can close this if you want.

**Comment by OmegaK2** [comment]
If you do ```pypoe_exporter dat json /path/to/out.json``` it will convert the the fields in the specification as well (will place placed in the "header" field), but it will only do it for the dat files exported. 
If you want to parse the spec into json, instead of implementing your own parser, it might just be easiest to write a script to dump the python config object into json

**Comment by eps1lon** [comment]
Nice that's just what i was looking for!
